from PyQt5 import QtCore, QtGui, QtWidgets
from Data.MessageBox import messageBox
from Model.Cliente import Client
from Admin.gestione_cliente.abbonamento_cliente import abbonamento_cliente
from Model.Abbonamento import Abbonamento


class aggiungi_cliente(object):
    objAbb = Abbonamento()
    messaggio = messageBox()

    def collega_window_abbonamento(self):
        self.window_abbonamento = QtWidgets.QMainWindow()
        self.ui = abbonamento_cliente()
        self.ui.setupUi(self.window_abbonamento)
        self.window_abbonamento.show()
        self.btnSave.show()

    def save(self):
        if self.txtName.text() != "" and self.txtCognome.text() != "" and self.txtluogonascita.text() != "" \
                and self.codfiscale.text() != "":
            oggetto = self.objAbb.getObj()
            cliente = Client(self.txtName.text().replace(" ",""), self.txtCognome.text().replace(" ",""), self.comboGender.currentText(),
                             self.dtdDataDiNascita.date(),
                             self.txtluogonascita.text(), self.codfiscale.text(), "1234", oggetto)

            cliente.addToList(cliente)
            cliente.scriviLista("./Admin/gestione_cliente/CredenzialiClienti.txt")
            self.saveWindow.close()
        else:
            self.messaggio.show_popup_listWidget("Uno o più campi risultano vuoti.")

    def setupUi(self, MainWindow):

        self.saveWindow = MainWindow
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(689, 495)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.lblTitle = QtWidgets.QLabel(self.centralwidget)
        self.lblTitle.setGeometry(QtCore.QRect(100, 20, 501, 91))
        font = QtGui.QFont()
        font.setFamily("Papyrus")
        font.setPointSize(24)
        font.setBold(True)
        font.setWeight(75)
        self.lblTitle.setFont(font)
        self.lblTitle.setObjectName("lblTitle")
        self.lblName = QtWidgets.QLabel(self.centralwidget)
        self.lblName.setGeometry(QtCore.QRect(180, 130, 61, 20))
        font = QtGui.QFont()
        font.setFamily("MS Gothic")
        font.setPointSize(13)
        font.setBold(False)
        font.setWeight(50)
        self.lblName.setFont(font)
        self.lblName.setObjectName("lblName")
        self.txtName = QtWidgets.QLineEdit(self.centralwidget)
        self.txtName.setGeometry(QtCore.QRect(270, 130, 181, 21))
        self.txtName.setObjectName("txtName")
        self.lblCognome = QtWidgets.QLabel(self.centralwidget)
        self.lblCognome.setGeometry(QtCore.QRect(170, 170, 91, 20))
        font = QtGui.QFont()
        font.setFamily("MS Gothic")
        font.setPointSize(13)
        self.lblCognome.setFont(font)
        self.lblCognome.setObjectName("lblCognome")
        self.txtCognome = QtWidgets.QLineEdit(self.centralwidget)
        self.txtCognome.setGeometry(QtCore.QRect(270, 170, 181, 21))
        self.txtCognome.setObjectName("txtCognome")
        self.lblGender = QtWidgets.QLabel(self.centralwidget)
        self.lblGender.setGeometry(QtCore.QRect(178, 210, 71, 20))
        font = QtGui.QFont()
        font.setFamily("MS Gothic")
        font.setPointSize(13)
        self.lblGender.setFont(font)
        self.lblGender.setObjectName("lblGender")
        self.lblWeight = QtWidgets.QLabel(self.centralwidget)
        self.lblWeight.setGeometry(QtCore.QRect(70, 290, 191, 20))
        font = QtGui.QFont()
        font.setFamily("MS Gothic")
        font.setPointSize(13)
        self.lblWeight.setFont(font)
        self.lblWeight.setObjectName("lblWeight")
        self.txtluogonascita = QtWidgets.QLineEdit(self.centralwidget)
        self.txtluogonascita.setGeometry(QtCore.QRect(270, 290, 181, 21))
        self.txtluogonascita.setObjectName("txtluogonascita")
        self.btnSave = QtWidgets.QPushButton(self.centralwidget)
        self.btnSave.setGeometry(QtCore.QRect(460, 380, 75, 24))
        font = QtGui.QFont()
        font.setFamily("MS Gothic")
        font.setBold(True)
        font.setWeight(75)
        self.btnSave.setFont(font)
        self.btnSave.setObjectName("btnSave")
        self.comboGender = QtWidgets.QComboBox(self.centralwidget)
        self.comboGender.setGeometry(QtCore.QRect(270, 210, 91, 22))
        self.comboGender.setObjectName("comboGender")
        self.comboGender.addItem("")
        self.comboGender.addItem("")
        self.lblWeight_2 = QtWidgets.QLabel(self.centralwidget)
        self.lblWeight_2.setGeometry(QtCore.QRect(80, 250, 181, 20))
        font = QtGui.QFont()
        font.setFamily("MS Gothic")
        font.setPointSize(13)
        self.lblWeight_2.setFont(font)
        self.lblWeight_2.setObjectName("lblWeight_2")
        self.lblWeight_3 = QtWidgets.QLabel(self.centralwidget)
        self.lblWeight_3.setGeometry(QtCore.QRect(90, 330, 171, 20))
        font = QtGui.QFont()
        font.setFamily("MS Gothic")
        font.setPointSize(13)
        self.lblWeight_3.setFont(font)
        self.lblWeight_3.setObjectName("lblWeight_3")
        self.codfiscale = QtWidgets.QLineEdit(self.centralwidget)
        self.codfiscale.setGeometry(QtCore.QRect(270, 330, 181, 21))
        self.codfiscale.setObjectName("codfiscale")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(460, 410, 101, 31))
        self.pushButton.setIconSize(QtCore.QSize(200, 200))
        self.pushButton.setObjectName("pushButton")
        self.dtdDataDiNascita = QtWidgets.QDateEdit(self.centralwidget)
        self.dtdDataDiNascita.setGeometry(QtCore.QRect(270, 250, 110, 22))
        self.dtdDataDiNascita.setCalendarPopup(True)
        self.dtdDataDiNascita.setObjectName("dtdDataDiNascita")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 689, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        self.btnSave.hide()
        self.pushButton.clicked.connect(self.collega_window_abbonamento)
        self.btnSave.clicked.connect(self.save)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pushButton.setText((_translate("MainWindow", "Abbonamenti")))
        self.lblTitle.setText(_translate("MainWindow", "Aggiungi i dati del cliente"))
        self.lblName.setText(_translate("MainWindow", "Nome"))
        self.lblCognome.setText(_translate("MainWindow", "Cognome"))
        self.lblGender.setText(_translate("MainWindow", "Sesso"))
        self.lblWeight.setText(_translate("MainWindow", "Luogo di nascita"))
        self.btnSave.setText(_translate("MainWindow", "Salva"))
        self.comboGender.setItemText(0, _translate("MainWindow", "maschio"))
        self.comboGender.setItemText(1, _translate("MainWindow", "femmina"))
        self.lblWeight_2.setText(_translate("MainWindow", "Data di nascita"))
        self.lblWeight_3.setText(_translate("MainWindow", "Codice Fiscale"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = aggiungi_cliente()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
